### ISSUE TITLE
cd-carousel & cd-read-more

### ISSUE THREAD

**Issue by pgroot91** [CodyHouse/cd-carousel-changelog#1]
Tried to implement the carousel in the read more component. Almost everything seems ok but the items are all 1px width. Must be some conflict or some sort. Tried to discover how to fix it but couldn't find the solution.

![image](https://user-images.githubusercontent.com/6934501/72013455-29556b80-325e-11ea-8ed3-4f65bec71434.png)

Any help would be highly appreciated 👍

**Comment by claudia-romano** [comment]
Hi there,
there's an issue when the carousel is inside a [sr-only](https://codyhouse.co/ds/docs/framework/accessibility#classes) class.
As a possible fix, you can add to the initCarouselLayout function, in the carousel.js file, the following code (on line 64):
```
// fix issue with hidden container
var closestHidden = carousel.listWrapper.closest('.sr-only');
if(closestHidden) {
  Util.removeClass(closestHidden, 'sr-only');
   containerWidth = carousel.listWrapper.offsetWidth;
   Util.addClass(closestHidden, 'sr-only');
}
```
<img width="662" alt="Screenshot 2020-01-10 09 04 12" src="https://user-images.githubusercontent.com/5512545/72136053-33738900-3388-11ea-9705-3349cc822320.png">

We are testing this solution (we'll push an update once we have completed the tests).

**Comment by pgroot91** [comment]
Thanks! 👍 for me it works like a charm.

**Comment by claudia-romano** [comment]
Great to hear that. We have included this fix in the component. Cheers!
