### ISSUE TITLE
Issue with responsive/resizing

### ISSUE THREAD

**Issue by dominicht** [CodyHouse/cd-carousel-changelog#10]
Hi,

I just noticed an issue when resizing a window with a carousel element. When you set different carousel items width using breakpoints, and resize the window, the carousel item's width won't change when reaching said breakpoint. We have to reload to get the correct sizes. See this video as an example: https://www.loom.com/share/7471db0629124f24a794abc4295914d0

Dominic

**Comment by claudia-romano** [comment]
Thanks for the heads up. We have pushed an update fixing this bug. You can get the updated JS code here:
https://codyhouse.co/ds/components/app/carousel

Feel free to reopen the issue if you are still experiencing the bug. Cheers
