### ISSUE TITLE
Issue with responsive/resizing

### ISSUE THREAD

**Issue by dominicht** [CodyHouse/cd-carousel-changelog#11]
Hi Claudia,

I'm reopening this issue since there is still a little bug with it. It fixed the problem with a carousel with px value for ```--carousel-item-auto-size```, but when using a % value (100%), it doesn't resize correctly. See video below:

https://www.loom.com/share/bb4ffe4370ec4de2ac0e3c254aa07486

_Originally posted by @claudia-romano in https://github.com/CodyHouse/cd-carousel-changelog/issues/10#issuecomment-641078817_

**Comment by claudia-romano** [comment]
Hi Dominic, we missed this! 

You can check the update version:
https://codyhouse.co/ds/components/app/carousel

Let me know if you are still getting the same bug. Thanks

**Comment by dominicht** [comment]
Great! Thanks again.
