### ISSUE TITLE
Suggestion: Add CSS class when both controls are disabled

### ISSUE THREAD

**Issue by dominicht** [CodyHouse/cd-carousel-changelog#12]
Hi,
I recently had an issue when the carousel had dynamic content in it. Sometimes, there wouldn't be enough items to allow the carousel to translate left & right on desktop. In this case, I wanted to completely hide the controls, but I didn't want to just with a `display: none;` on the disabled controls since I still want those visible when there are enough items.

To fix this, I added the following code inside the `resetCarouselControls` function in the .js file around line 479:

```
function resetCarouselControls(carousel) {
    ...
    if(carousel.controls.length > 0) {
      ...
      (carousel.totTranslate == 0 && (carousel.totTranslate == (- carousel.translateContainer - carousel.containerWidth) || carousel.items.length <= carousel.visibItemsNb))
        ? Util.addClass(carousel.element, 'carousel--controls-off')
        : Util.removeClass(carousel.element, 'carousel--controls-off');
    }
    ...
```

With this `carousel--controls-off` CSS class, I'm able to hide elements (controls, pagination, counters) if both controls are off. I'm not sure if you want to implement this, but I thought this could be useful to others.

Dominic

**Comment by claudia-romano** [comment]
Hi Dominic,
thanks for the suggestion. It makes sense to completely hide the controls in those cases. 
We have updated the component to included the new `carousel--hide-controls` class. 

Cheers,
