### ISSUE TITLE
Issue with dragging on a desktop

### ISSUE THREAD

**Issue by dominicht** [CodyHouse/cd-carousel-changelog#13]
When the dragging option is on, I sometimes encounter an issue on desktop where the drag would get stuck after clicking on an anchor element and slightly dragging once. It would keep on dragging left and right following my cursor movements after the simple click until I move my cursor away from the carousel. 

See example below (if I click outside of the anchor, it behaves correctly, but when I click on the anchor, it gets stuck):
https://www.loom.com/share/e2318a3eccd34e7590dadda685f86394

Dominic

**Comment by claudia-romano** [comment]
Hi Dominic, you should prevent your anchor items from being draggable. Something like:
```<a href="#0" ondragstart="return false;">Link</a>```
That should fix your issue.

**Comment by dominicht** [comment]
Hi Claudia,
This does indeed prevent the dragging, however if I now want to click and drag the carousel to view the next ones on desktop and click on an anchor, it will also follow the anchor link. Maybe if something like a `preventDefault()` while clicking and dragging could help?

**Comment by dominicht** [comment]
I dug into the code a bit and fixed the anchor clicking issue by doing the following changes (in addition of the ondragstart="return false;"):

```
carousel.element.addEventListener('dragStart', function(event){
        ...
        // REMOVED THIS HERE
        //Util.addClass(carousel.element, 'carousel--is-dragging');
        ...
      });
      carousel.element.addEventListener('dragging', function(event){
        ...
        // ADDED THIS HERE INSTEAD
        if(Math.abs(event.detail.x - carousel.dragStart) > 10) Util.addClass(carousel.element, 'carousel--is-dragging');
        ...
      });
```

I then added the following CSS:

```
.carousel--is-dragging a {
  pointer-events: none;
}
```

I'm not sure if it's the best way to achieve this, but it seems to work for now. Let me know if you have any better ideas.

**Comment by claudia-romano** [comment]
This issue is not strictly related to the carousel, but it is a general issue with links being dragged/links inside a draggable element. 
Probably the solution should target those links regardless of the component they are in. Something like this should work (I have not properly tested it though):
```js
link.addEventListener('dragstart', function(event){ // link -> <a> inside a draggable element
  event.preventDefault();
  preventFirstClick(link);
  return false;
});

function preventFirstClick(link) {
  link.addEventListener('click', function cb(event){
    event.preventDefault();
    link.removeEventListener('click', cb);
  });
};
```
We are not planning on making changes to the carousel for this reason. But the solution you suggested works great. Cheers!
