### ISSUE TITLE
Suggestion: Adding a custom event returning active item(s)

### ISSUE THREAD

**Issue by dominicht** [CodyHouse/cd-carousel-changelog#14]
For a project, I used the carousel component to create a hero slideshow and I also have a header overlapping the carousel. Each carousel item has a different `data-theme` and also I want to dynamically change the header's color theme based on the current active carousel item.

I tried using `carousel.addEventListener('carousel-updated', function(event){});`, but it only returns the list of clones and I needed the active items.

I'm not sure if I missed something, but it would be nice if either this same event also returned the active items or if another event would do this. I also noticed that this event is only triggered when navigating a first time, it isn't triggered when initiating the carousel. It could be useful to have this triggered on init.

Dominic

**Comment by claudia-romano** [comment]
Hi Dominic,
the `carousel-updated` event is only emitted when new clones are created (which may not be the case if you are simply switching from an item to the next one).

We have now included a new custom event (`carousel-active-items`) that you can use. More info here:
https://codyhouse.co/ds/components/info/carousel#active-items

Cheers!
