### ISSUE TITLE
Issue with fullwidth carousel on safari iOS

### ISSUE THREAD

**Issue by dominicht** [CodyHouse/cd-carousel-changelog#15]
Hi,

On safari iOS (latest version), there is an issue with the carousel navigation when the items' width is set to 100% (to create a slideshow) and loop is turned on. The first few slides, navigation will occur correctly but then, the next/previous buttons will stop working until you swipe on the carousel, which results in a glitch.

Here is a video of the issue:
https://www.loom.com/share/ae415259eae44d1a8046a7c8827840c2

Dominic

**Comment by claudia-romano** [comment]
Hi Dominic,
are you able to recreate the issue only using the carousel component with the proper options (e.g., loop on, width 100%) but with no additional custom code? 
I've been testing the component demo on Safari iOS but I was not able to recreate the issue. Thanks.

**Comment by dominicht** [comment]
Hi Claudia,

Sure, here is a URL: http://carousel.huysmans.me/index.html

The code I used is the following:

```
<div class="my-carousel carousel flex flex-column js-carousel" data-drag="on">
      <p class="sr-only">Carousel items</p>

      <div class="carousel__wrapper order-2 overflow-hidden">
        ...
```

And CSS:
```
.my-carousel {
	--carousel-item-auto-size: 100vw;
	--carousel-grid-gap: 0;
}
```

Here is a video recording:
https://www.loom.com/share/33276d1018c54adc9b1d0d01b4f84505

Dominic

**Comment by dominicht** [comment]
I just noticed that you can also reproduce this is safari on desktop. I'm using safari 14.0.

**Comment by claudia-romano** [comment]
Hi Dominic, safari 14.0 has not been released yet. Am I correct? Unfortunately we do not test on those versions (or fix bugs) as those versions may be modified before they are released. 

May I ask you what version of safari iOS are you using? Thanks.

**Comment by dominicht** [comment]
Yeah I figured. 

For iOS, I saw this on the version that comes with 13.6.1. (Tried on 2 different phones)

**Comment by dominicht** [comment]
Hi, I just updated a phone from 13.6.1 to 13.7 and the issue seems to be resolved on that one. As for 14.0, I'll just keep an eye out when it's officially released and see if it still needs attention. I'll keep you posted if I find anything else. Thanks!

**Comment by claudia-romano** [comment]
Great! Thanks for the update. 
I'm closing this now. Feel free to reopen it if anything changes with the new Safari version. Cheers!

**Comment by dominicht** [comment]
Hi @claudia-romano 
With the official release of iOS 14, the issue is still happening, can we reopen this issue?

**Comment by claudia-romano** [comment]
Hi Dominic, we are looking into this issue and will update the component as soon as we have a fix. Thanks.

**Comment by claudia-romano** [comment]
We have just pushed an updated version of the carousel component fixing this issue. You can get the updated JS code here:
https://codyhouse.co/ds/components/app/carousel

Feel free to reopen this issue if you are still experiencing problems. Cheers!
