### ISSUE TITLE
Links within carousel components are not clickable (or require double-click) on mobile when data-drag="on"

### ISSUE THREAD

**Issue by emilycritter** [CodyHouse/cd-carousel-changelog#16]
1. On mobile, I sometimes have to double-click (or click and hold) on a link within a carousel to trigger the link
2. Add a link to a carousel item; try to use that link on mobile
3. Safari, iPhone X
4. Carousel on this page: https://intalytics.com/real-estate-solutions/#solutions (CTA is clickable)
Carousel at the bottom of this page: https://intalytics.com/intalytics-commentary-no-miracle-on-34th-street/ (whole card is clickable)
5. 

![carousel](https://user-images.githubusercontent.com/16456162/92836619-3e147100-f3a2-11ea-8875-c0ea44f231bf.gif)

**Comment by emilycritter** [comment]
Update: this issue is resolved with `data-drag="off"`, but we'd ideally like to keep this feature.

**Comment by claudia-romano** [comment]
Hi there,
the double-tab issue on iOS is due to the link hover effect (first tap -> hover effect, second tap -> redirect).

You can read more about that here:
https://css-tricks.com/annoying-mobile-double-tap-link-issue/

I'm closing this issue as this is not related to the carousel component (or the drag option).

Feel free to reopen it if you can recreate the bug using our basic demo carousel + drag (no additional custom style/js). Cheers!

**Comment by emilycritter** [comment]
We do not encounter this issue on other buttons that use the same styling (on the site referenced in this Issue or on other sites we've build using Codyhouse). 

None of the Codyhouse carousel demos include any buttons, so I can't show you the bug using that code. 

Here is a basic full-width carousel where the two slides include links with no hover effects:
https://user-images.githubusercontent.com/16456162/108784234-92687300-7534-11eb-8dde-f37b2f85fa04.MP4
* This behavior leads me to believe that the hover issue you identified is unrelated


Can you please help @claudia-romano ? I don't have permission to re-open this issue.

**Comment by emilycritter** [comment]
After doing some debugging, I'm led to believe this issue is a result of the swipe-content component starting the drag functionality on touchstart. As a result, the click event (on a child element) does not register. 

jQuery's draggable widget circumvents this issue by including a `cancel` option: https://api.jqueryui.com/draggable/#option-cancel. Perhaps the CodyHouse swipe-content / carousel components could implement something similar (and include `input, textarea, button, select, option, .btn` as defaults).

**Comment by emilycritter** [comment]
I'm not yet sure if there are side effects to this change, but knowing that we want users to be able to click on `.btn` elements within a carousel, adding line 39 in _1_swipe-content.js works:
![image](https://user-images.githubusercontent.com/16456162/108886558-b9738300-75ce-11eb-88fa-5de7abe4a44a.png)

**Comment by claudia-romano** [comment]
Hi Emily, please take a look at this issue:
https://github.com/CodyHouse/cd-carousel-changelog/issues/13

**Comment by emilycritter** [comment]
I will check it out, thank you!
