### ISSUE TITLE
Carousel only on mobile

### ISSUE THREAD

**Issue by alebarbaja** [CodyHouse/cd-carousel-changelog#19]
Hi, I want to transform a list of elements on carousel only for mobile. Is this possible with this component? Thanks!

**Comment by sebastiano-guerriero** [comment]
Hi, you can change the number of visible carousel items at different breakpoints by updating the --carousel-item-auto-size value. More info here: https://codyhouse.co/ds/components/info/carousel#slideshow

**Comment by claudia-romano** [comment]
Closing this as no additional info was provided. Feel free to reopen it if you need more info. Cheers!
