### ISSUE TITLE
carousel breaking all other js being used within the carousel after completing a loop

### ISSUE THREAD

**Issue by starchild** [CodyHouse/cd-carousel-changelog#2]
Hi,

We have an issue whereby the carousel itself seems to work fine, but after it completes one loop of the listed items, whatever js is contained within that carousel no longer works.

At first I thought it was other js being the culprit, but I've pretty much removed all other js except for utils, carousel and the custom js that breaks.

It doesn't matter what the js is, I've tested it with different functions, and each time, the function breaks once the carousel completes 1 loop.

I can show you a demo, but I'd prefer to do it in private if that's ok.

I hope this makes sense.

Thank you.

**Comment by w3work** [comment]
Perhabs this is relevant or not, we used the carousel in one of our projects and it is working fine.
Have a look here: https://www.azv-muldental.de/ueber-uns
But on this site, the version 1.0.0 is implemented.

**Comment by starchild** [comment]
The carousel itself works fine, but, for example, we have product images that have a href that is generated via js, and the href works fine, until the loop is completed, and then it fails.  

Another eg is each product might have multiple images - we show these using owl carousel.  Every thing works fine, again until a loop is completed and then owl carousel breaks.

The carousel itself continues to work, but it kills what ever js is inside it after a complete loop, if the contents employ any js at all.

**Comment by starchild** [comment]
.. and yes, we're using v2

**Comment by claudia-romano** [comment]
Hi there, thanks for the heads up. No need to share the url, I can see the nature of the problem here. We are looking into this.

Meanwhile, may I ask if you are importing your custom js file after the carousel js? If you are, could you try importing it before the carousel js and let me know if this fixes your issue? Thank you.

**Comment by starchild** [comment]
Hi Claudia, 

I've already tried all combinations of sort ordering, and nothing makes a difference.

**Comment by starchild** [comment]
Hi Claudia, just wondering if you've managed to create a fix for this yet?

**Comment by claudia-romano** [comment]
Hi, we are still looking into this issue. The plugin removes the items and reinsert clones of those items when required. This could be the reason of the issue you are experincing.
 
About you specific case: does your custom code set the href at loading time or on click? 

If it's at loading time, then a possible solution would be to initialize the carousel after the href has been set. To do that:
- remove the ```.js-carousel``` class from the ```.carousel``` element;
- in your custom code, once the hrefs have been set, add:
```
new Carousel({element: carouselEl, autoplay : false,  drag: false});
``` 
Where the ```carouselEl``` is the ```.carousel``` element.

**Comment by starchild** [comment]
Yes, that would make sense.  I'll try that today and let you know how I go.

**Comment by starchild** [comment]
Doesn't work I'm afraid - we get "uncaught TypeError: this.element.getElementsByClassName is not a function" error.

**Comment by claudia-romano** [comment]
Could you please double check there was no error while initializing the Carousel object? In the code I provided above, ```carouselEl``` needs to be the carousel object. For example if you add ```id="carousel-1"``` to the ```.carousel``` element, then you would have:
```
var carouselEl = document.getElementById('carousel-1');
```

Thanks.

**Comment by starchild** [comment]
I made it like this:

`<div class="carousel js-carousel-2" data-drag="on" data-autoplay="on" data-autoplay-interval="5000">`

and then in the js fie that is loaded later on...

`new Carousel ({
    element: 'js-carousel-2', 
    autoplay : false,  
    drag: false
});`


I didn't make any other changes.

**Comment by claudia-romano** [comment]
Could you please follow these steps:
- Remove the .js-carousel class from .carousel;
- Add the 'carousel-1' id to the .carousel;
- Then use:
```
new Carousel ({ element: document.getElementById('carousel-1'), autoplay : false, drag: false });
```

**Comment by starchild** [comment]
Same as original issue.  Carousel shows and works, but js breaks after 1 loop.

`<div id="carousel-1" class="carousel" data-drag="on" data-autoplay="on" data-autoplay-interval="5000">`

`
new Carousel ({ element: document.getElementById('carousel-1'), autoplay : false, drag: false });   `

**Comment by claudia-romano** [comment]
If you are getting the same issue, then it should mean your js creates the custom href on click rather than on page load. 

For the carousel to work properly, we need to create clones of the original items, and this does not copy event listeners (e.g., on click).

Would that be possible to change your custom js to set the href first (on load and not on click) and then initialize the carousel? Thanks.

**Comment by starchild** [comment]
Hi . :)

I'm pretty sure it's on load.  If we include other js, such as owl-carousel on the images within the carousel, it breaks also does the same thing.  Owl is definitely onload.  I'll ask my devs tonight to confirm, but I'm sure it's onload.

**Comment by claudia-romano** [comment]
Hi there, sorry I probably was not clear in my message. When I say onload, I mean that the custom href values are set on load (your script searches for the links and immediately set the href, it does not wait for the link to be clicked).

The owl carousel uses click/drag/swipe events (when controls are clicked or items are dragged, it updates the carousel). So it is not onload. Thanks!

**Comment by starchild** [comment]
Hmmm. So I guess then we'll need to find another carousel.  I don't think I'll be the only one that will be employing js within the carousel though - whether it's a gallery, js links, js based qty selectors, or image magnifiers etc... there's plenty of use cases where js might play a role within the carousel items.

It would be really fantastic to have a real solution for this/ In the meantime though, we'll need to find something outside the CH component family. 

Bugger

**Comment by starchild** [comment]
hi, just wondering if there's any update to this perhaps?

**Comment by claudia-romano** [comment]
Hi, we are still working on this issue. Sorry about that.

If you still have a demo of this issue, you could send it at help@codyhouse.co. We would like to double-check it before releasing an updated version. Thanks.

**Comment by starchild** [comment]
email sent.

**Comment by claudia-romano** [comment]
Hi there, thanks for the additional info.
As for the nature of the carousel (infinite looping), custom JS code applied to the carousel items (e.g., event listeners) are not preserved after a single loop.
You can solve this problem re-initializing your custom code when new clones are created. We have added a custom 'carousel-updated' event that helps doing that. You can find more info on the component page:
https://codyhouse.co/ds/components/info/carousel

In your case, you should do something like:
```
var carousel = document.getElementsByClassName('js-carousel')[0];
carousel.addEventListener('carousel-updated', function(event){
  // event.detail -> list of clone items
  for(var i = 0; i < event.detail.length; i++) {
    var owlCarousel = event.detail[i].getElementsByClassName('owl-carousel');
    if(owlCarousel.length > 0) {
      $(owlCarousel[0]).owlCarousel({
         // options here
      });
    }
  }
});
```
This should fix your issue.

**Comment by starchild** [comment]
Thank you for your reply Claudia. 

 I've tried this code, in multiple locations and it's not working as intended.

I added the following:

```
var carousel = document.getElementsByClassName('js-carousel')[0];
carousel.addEventListener('carousel-updated', function(event){
  // event.detail -> list of clone items
  for(var i = 0; i < event.detail.length; i++) {
    var owlCarousel = event.detail[i].getElementsByClassName('owl-carousel');
    if(owlCarousel.length > 0) {
      $(owlCarousel[0]).owlCarousel({
        loop: false,
        rewind: true,
        lazyLoad: true,
        margin: 10,
        dots: true,
        autoplayTimeout:3000,
        autoplaySpeed: 1000,
  	dotsSpeed: 1000,
        responsive: {
            0: {
                items: 1
            },
            600: {
                items: 1
            },
            1000: {
                items: 1
            }
        }
      });
    }
  }
}); 
```

... to the very bottom of the carousel js, inside the last closing statement of the carousel js and later on at the end of the page - none of which seems to work.

Exactly where should it go please?

**Comment by claudia-romano** [comment]
Hi there,
you do not need to include it in the carousel.js. But make sure to include it after carousel.js and owl-carousel.js. 

Also, could you please confirm you have updated the carousel.js with the latest version? 
https://codyhouse.co/ds/components/app/carousel

Thanks.

**Comment by starchild** [comment]
Yes, fixed!  

I saw it fixed on home, but broken on an inner page carousel - then realised the code was a slightly diff in both, but now all are fixed.

Thank you so much Claudia.  You and the team are superstars <3
