### ISSUE TITLE
Detect last item visible inside carousel

### ISSUE THREAD

**Issue by alebarbaja** [CodyHouse/cd-carousel-changelog#22]
There is a way of detect the last carousel item visible on the wrapper? Specifically I need to change styles of that element, the last carousel item visible.

<img width="1326" alt="Screenshot 2021-04-29 at 12 25 27" src="https://user-images.githubusercontent.com/28918805/116537118-17318d80-a8e6-11eb-9810-2c767f24ec3c.png">

Thanks!

**Comment by claudia-romano** [comment]
Hi there,
you can use the `carousel-active-items` event. This event can be used to detect the first visible item in the carousel, and the total number of visible items.
Take a look at the [Active Items Event section](https://codyhouse.co/ds/components/info/carousel#active-items) for more info.

**Comment by claudia-romano** [comment]
Closing this as no additional info was provided. Feel free to reopen it if you need additional info. Cheers!
