### ISSUE TITLE
Autoplay and Loop

### ISSUE THREAD

**Issue by matobeag** [CodyHouse/cd-carousel-changelog#24]
I am having trouble getting the autoplay and loop functions to work simultaneously.

https://codepen.io/matobe/pen/KKxbeZE

**Comment by claudia-romano** [comment]
Hi there, the loop option is off when you add the carousel navigation. More info here:
https://codyhouse.co/ds/components/info/carousel#options

Alternatively, you can use the Slideshow component to achieve the same result:
https://codyhouse.co/ds/components/info/slideshow
