### ISSUE TITLE
Links within a carousel on mobile not working. 

### ISSUE THREAD

**Issue by pattyok** [CodyHouse/cd-carousel-changelog#25]
I have a carousel where each item is a link. When dragging is turned on the links are not working. The code registers a touch as a click, but the click on the linked element isn't propagating. Wondering if this is a known issue and if you have any solution for that.

**Comment by claudia-romano** [comment]
Hi Patty,
this is an issue with clickable elements inside a draggable container. Please take a look at this issue https://github.com/codyhouse/cd-carousel-changelog/issues/13 where a solution is provided.

I'm closing this, but feel free to reopen it if you are still having problems. Cheers!
