### ISSUE TITLE
Remove Infinite loop from carousel

### ISSUE THREAD

**Issue by dominicht** [CodyHouse/cd-carousel-changelog#3]
This is more of a feature request for this component, but I was wondering if it's possible to prevent the infinite loop from the carousel (cloning of elements). There are some scenarios where you don't necessarily want this behavior. It would be nice if this could be toggled with something like `data-infinite="on"`.

**Comment by sebastiano-guerriero** [comment]
Good idea! We have this on our roadmap. We're not sure yet if we should create a new component or create a variation of the existing one, but we're looking into it.

**Comment by dominicht** [comment]
Thanks for the quick answer @sebastiano-guerriero. 

I'm using the framework on a project as we speak and needed to use the Slideshow and Carousel components. I looked at the JS and thought the 2 are very similar could easily be combined and combining the functionalities wouldn't add too much code (even save some if using both). In my opinion, it would be logical to have 1 plugin for this. Something similar to [Slick.js](https://kenwheeler.github.io/slick/), but still keeping it simple.

I also thought the same about the Drawer and Modal components.

It's just my input, but regardless, keep up the great work.

**Comment by sebastiano-guerriero** [comment]
Thanks for the feedback! We'll definitely look into merging the components. We've recently done the same for the Tabs component, where we've created a new "source" version with only the functionality and almost no style, and all the variations now depend on this source version. I'll update this thread as soon as we have news.

**Comment by claudia-romano** [comment]
Hi there,
the carousel component has now a data-loop option that you can set to "off".

Also, if you are using both the Slideshow and the Carousel, you may consider using only the Carousel component and setting it to show one slide at a time. You can find more Info on the Carousel Info page:
https://codyhouse.co/ds/components/info/carousel#item-number

Cheers!

**Comment by dominicht** [comment]
Amazing work. This is perfect!
