### ISSUE TITLE
Carousel dots are not updated on window resize

### ISSUE THREAD

**Issue by emilycritter** [CodyHouse/cd-carousel-changelog#4]
1. Short description of the bug
- The carousel dots are not updated when the window is resized

2. Steps to reproduce the bug
- Set data attributes for `data-loop` and `data-navigation`:
```
<div class="carousel js-carousel" data-drag="on" data-loop="off" data-navigation="on">
```

3. Browser + Operating system
- I've seen this issue in both Chrome and Safari. It does not look to be browser-specific

![carousel-nav](https://user-images.githubusercontent.com/16456162/79160389-522a5700-7d9f-11ea-9507-762a831119c9.gif)

**Comment by claudia-romano** [comment]
Hi there, thanks for the heads-up. We just pushed an updated version of the component that should fix the issue. You can get the updated JS code from the component page:
https://codyhouse.co/ds/components/app/carousel

Let me know if you are still experiencing it.

Cheers

**Comment by emilycritter** [comment]
Y'all are great! Thank you!!
