### ISSUE TITLE
Carousel items are not centered (when data-loop="off")

### ISSUE THREAD

**Issue by emilycritter** [CodyHouse/cd-carousel-changelog#5]
1. Short description of the bug
- The carousel is not centered when there are just a few carousel items

2. Steps to reproduce the bug
- Turn off data loop
- Remove carousel items until the carousel no longer spans the width of the container
<div class="carousel js-carousel" data-drag="on" data-loop="off">

3. Browser + Operating system
- NA

![image](https://user-images.githubusercontent.com/16456162/79241179-52c2fc00-7e38-11ea-95f1-7dabf02a8b9f.png)

**Comment by claudia-romano** [comment]
Hi there,
this is the default behavior of the carousel. You can use the data-justify-content="on" option to center them:
https://codyhouse.co/ds/components/info/carousel#center-items

This is a new option so you may need to upgrade to the latest version. Cheers!
