### ISSUE TITLE
Small error in the documentation

### ISSUE THREAD

**Issue by dominicht** [CodyHouse/cd-carousel-changelog#7]
Hi,

I just noticed that in your documentation for the carousel, you indicate that in order to display the counter total, you must have an element with a `.js-carousel__counter-total` class. However, this class doesn't work and you need to use the following class instead: `.js-carousel__counter-tot`.

Dominic

**Comment by claudia-romano** [comment]
Hi Dominic, thanks for the heads-up! This has been fixed:
https://codyhouse.co/ds/components/info/carousel#counter

Cheers!
