### ISSUE TITLE
Carousel counter shows incorrect total with loop

### ISSUE THREAD

**Issue by dominicht** [CodyHouse/cd-carousel-changelog#8]
I'm using the carousel component as a slideshow with the counter element. The counter index is correct, however, the counter total is displaying 3 when I have only 2 items. It seems like the JS is also calculating clones which could cause this (I'm using the loop functionality).

Here is a video of the issue: https://www.loom.com/share/f10f982671ac43a1b772174be553e054

**Comment by claudia-romano** [comment]
Yes the issues was with the cloned items. It has been fixed now. You can get the updated js code form the component demo page:
https://codyhouse.co/ds/components/app/carousel

Feel free to reopen the issue if you are still having problems. Cheers!
