### ISSUE TITLE
reduce the width on mobile

### ISSUE THREAD

**Issue by omarherri** [CodyHouse/cd-carousel-changelog#9]
First i wanna thank you for the amount of work you do for the community. Whithout you it would be hardfull for us to do 20% of your work.

I have a question about this component. On mobile the width is 100% but i want to be able to split the caroussel in 2 items, so each items take 50% of the width. is there a hack i can use.

**Comment by sebastiano-guerriero** [comment]
Hi there, and thanks your kind words!

To modify the number of visible items, you should edit the --carousel-item-auto-size custom property.

More info here:
https://codyhouse.co/ds/components/info/carousel#item-number

Cheers

**Comment by omarherri** [comment]
Yes it works now. Thanks a lot.
